# Generated by Django 3.2 on 2023-02-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number_store', models.IntegerField(verbose_name='Number Store')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('patrimony', models.CharField(max_length=50, unique=True, verbose_name='Nº patrimony')),
                ('obs', models.TextField(max_length=255, verbose_name='Observation')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='inventory.category')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
